

//auth system


export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"

export const CHANGE_PROFILE_IMAGE = "CHANGE_PROFILE_IMAGE"
export const SOCKET = "SOCKET"
export const LOGIN_SUCCES = "LOGIN_SUCCES"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGOUT = "LOGOUT"



//Items

export const CREATE_ITEM = "CREATE_ITEM";
export const FETCH_ITEM = "FETCH_ITEM"
export const FETCH_ITEMS = "FETCH_ITEMS"
export const EDIT_ITEM = "EDIT_ITEM"
export const SUCCESS_CREATION_ITEM = "SUCCESS_CREATION_ITEM"
export const FETCH_MYFRIPS = "FETCH_MYFRIPS"
export const LOADING_ITEM = "LOADING_ITEM"
export const FETCH_NEW_ITEMS = "FETCH_NEW_ITEMS"
export const GET_MORE_ITEMS = "GET_MORE_ITEMS"



export const FETCH_ID_FAVORITE = "FETCH_ID_FAVORITE"




//Messages

export const NEW_MESSAGE = "NEW_MESSAGE"
export const GENERATE_CONV = "GENERATE_CONV"
export const GET_ALL_CONV = "GET_ALL_CONV"
export const GET_CONV = "GET_CONV"
export const GET_LASTMESSAGE ="GET_LASTMESSAGE"
export const ADD_MORE_MESSAGE ="ADD_MORE_MESSAGE"
export const ADD_MESSAGE_IMAGE ="ADD_MESSAGE_IMAGE"


export const GET_MORE_MESSAGE = "GET_MORE_MESSAGE"
export const HAS_MORE = "HAS_MORE"
export const NO_MORE = "NO_MORE"

export const MESSAGE_ERROR = "MESSAGE_ERROR"
export const MESSAGE_LOADING = "MESSAGE_LOADING"

export const GET_MORE_MESSAGE_LOADING = "GET_MORE_MESSAGE_LOADING"
export const GET_MORE_MESSAGE_ERROR = "GET_MORE_MESSAGE_ERROR"
export const Page_NUMBER = "Page_NUMBER"

export const GET_CONV_ERROR = "GET_CONV_ERROR "
export const GET_CONV_LOADING = "GET_CONV_LOADING"





export const MSG_ERROR ="MSG_ERROR"

//Favorite

export const ADD_FAVORITE = "ADD_FAVORITE"
export const FETCH_MYFAVORITEIDs = "FETCH_MYFAVORITEIDs"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"
export const FETCH_MYFAVORITE = "FETCH_MYFAVORITE"

//Filter

export const FILTER = "FILTER"
export const FETCH_ITEM_TYPE = "FETCH_ITEM_TYPE"
export const FETCH_NEW_ITEM_TYPE = "FETCH_NEW_ITEM_TYPE"
export const FETCH_ITEM_FILTER_SUCCESS = "FETCH_ITEM_FILTER_SUCCESS"
export const CHANGE_PAGINATION = "CHANGE_PAGINATION"


export const ADD_FILTER = "ADD_FILTER" 
export const REMOVE_FILTER = "REMOVE_FILTER" 
export const CREATE_CHIPS = "CREATE_CHIPS" 

export const FETCH_FILTER = "FETCH_FILTER"


/// ITEMFORPROPOSE ///¨
export const GET_ITEM_PROPOSE = "GET_ITEM_PROPOSE"
export const GET_ITEM_PROPOSE_LOADING = "GET_ITEM_PROPOSE_LOADING"

export const GET_ITEM_PROPOSE_FROMID = "GET_ITEM_PROPOSE_FROMID"
export const GET_ITEM_PROPOSE_LOADING_FROMID = "GET_ITEM_PROPOSE_LOADING-_FROMID"

export const GET_ITEM_ID_PROPOSE = "GET_ITEM_ID_PROPOSE"

export const HANDLE_SECOND_PAGE = "HANDLE_SECOND_PAGE"
export const HANDLE_AWAYSECOND_PAGE = "HANDLE_AWAYSECOND_PAGE"


export const HANDLE_CLICK_FORPROPOSE = "HANDLE_CLICK_FORPROPOSE"
export const HANDLEAWAY_CLICK_FORPROPOSE = "HANDLEAWAY_CLICK_FORPROPOSE"

export const DISPATCH_HANDLECLICK = "DISPATCH_HANDLECLICK"

/// PATHNAME ///


export const SET_PATH = "SET_PATH"


/// GETINFOITEM ///
export const INFO_ITEM = "INFO_ITEM"

/// ERROR ///
export const ERROR = "ERROR"


/// NOTIFICATION
export const NOTIFICATION = "NOTIFICATION"
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION"
export const UNREAD_NOTIFICATION  = "UNREAD_NOTIFICATION"
export const NEW_NOTIFICATION = "NEW_NOTIFICATION"
export const READ_MESSAGE = "READ_MESSAGE"





